### ISSUE TITLE
加载的弹幕格式

### ISSUE THREAD

**Issue by ZD511** [JiaJiaJiang/NyaP#12]
大佬，有没有弹幕格式的样例文件呀，那个json格式的

**Comment by JiaJiaJiang** [comment]
为了兼容性考虑，播放器是通过代码加载弹幕的，不会自己解析json文件，加载方式可以参考这里 :https://github.com/JiaJiaJiang/SimpleDanmakuSite/blob/5e9baddf54e09c7d1525e190b4904e0da260ed11/static/playPage.js#L185

关于这个弹幕object属性的含义可以参考这里:https://github.com/JiaJiaJiang/NyaP/blob/6e716b16622a35a39fc8f839919da9fa115ad750/component/NyaP-Danmaku/src/danmaku-text/danmaku-text.js#L16
`msec time`指视频进度的毫秒数，`style`参考此文件下面的`defaultStyle`对象定义，`mode`参考紧接的下一个注释，`onScreen`不要写，这是一个内部属性。

其它出现在加载示例里但在object定义里没有出现的属性属于给插件使用的额外内容，不要在意。
